### ISSUE TITLE
FileMigrationTask barfs on files without an extension

### ISSUE THREAD

**Issue by phptek** [silverstripe/silverstripe-assets#359] opened 2019-12-12 22:17 UTC
Scenario:

* Upgraded codebase and DB from v3.7 to v4.3
* dev/build
* dev/tasks/MigrateFileTask
* Observe that errors are emitted for files where `$fileInfo['extension']` cannot be assumed to have been populated. Looking at my current legacy assets dir, I can see several instances of files having been uploaded without a file-extension (I have no idea how this happens, I just know that it has)

Examples:

```
#> for file in $(find assets/Images/Buses-transport/Total-mobility/_resampled/ -type f); do echo $file | grep -v '\.'; done
assets/Images/Buses-transport/Total-mobility/_resampled/ScaleWidthWzQwMF0-Total-Mobility-client
assets/Images/Buses-transport/Total-mobility/_resampled/stripthumbnailW10-Total-Mobility-client
assets/Images/Buses-transport/Total-mobility/_resampled/stripthumbnailW10-TRC26
assets/Images/Buses-transport/Total-mobility/_resampled/ScaleWidthWzQwMF0-TRC26
```

The error:

```
ERROR [Notice]: Undefined index: extension
IN GET dev/tasks/MigrateFileTask
Line 165 in /vagrant/vendor/silverstripe/assets/src/Dev/Tasks/LegacyThumbnailMigrationHelper.php

Source
======
  156:             // Image->manipulate() is in charge of creating the full file name (incl. variant),
  157:             // and assumes the manipulation is run on an existing original file, so we can't use it
       here.
  158:             // Any AssetStore-level filesystem operations (like move()) suffer from the same
       limitation,
  159:             // so we need to drop down to path based filesystem renames.
  160:             $newResampledPath = implode('', [
  161:                 $folderPath,
  162:                 $fileInfo['filename'],
  163:                 '__',
  164:                 implode('_', $encodedVariants),
* 165:                 '.' . $fileInfo['extension']
  166:             ]);
  167: 
  168:             // Don't overwrite existing files in the new location,
  169:             // they might have been generated based on newer file contents
  170:             if ($filesystem->has($newResampledPath)) {
  171:                 $filesystem->delete($oldResampledPath);

Trace
=====
Monolog\ErrorHandler->handleError(8, Undefined index: extension, /vagrant/vendor/silverstripe/assets/src/Dev/Tasks/LegacyThumbnailMigrationHelper.php, 165, Array)
LegacyThumbnailMigrationHelper.php:165
```

**Comment by emteknetnz** [comment] 2019-12-16 21:36
Related issue https://github.com/silverstripe/silverstripe-framework/issues/9037

**Comment by emteknetnz** [comment] 2019-12-16 21:40
Looks as though this issue was already discussed in June on the framework repo.  I've linked it above.  Thinking there along the lines of having this fail gracefully rather than allow the migration to occur

**Comment by phptek** [comment] 2019-12-16 21:49
+1 to fail gracefully. My vote is to just skip these "invalid" files. I suppose the logic could run file -i over them and use the mine info it returns in these cases. Skipping is easier though!

**Comment by chillu** [comment] 2020-02-03 19:50
Closing as a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/9037 (the task lives on framework)

**Closed by chillu** 2020-02-03 19:50 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug
