### ISSUE TITLE
upgrading to SS4 leads to discrepancy between DRAFT and LIVE table

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-assets#305] opened 2019-07-26 03:54 UTC
After upgrading from SS3 to SS4, I end up with the following difference:

... Found a column in the DRAFT table that did not match the LIVE table: Filename
... Found a column in the DRAFT table that did not match the LIVE table: Content
... Found a column in the DRAFT table that did not match the LIVE table: CurrentVersionID

Is that a worry? Obviously these are obsolete, but what should I with them?

**Comment by maxime-rainville** [comment] 2019-08-02 05:36
Filename and Content are legacy columns from SS3 that are no longer there in SS4.  Not sure about `CurrentVersionID`.

When you run a `dev/build`, columns the ORM doesn't know about won't be dropped. You will not be able to access them directly through the ORM however. When the File_Live and File_Versions get created, they won't get these extra columns.

It's actually important to have the `Filename` column around, because the `FileMigrationTask` will read it to generate the value for the `FileFilename` column.

After you've run the File Migration, you should be able to drop those columns without  any side effect.

Closing as this is expected behavior.

**Closed by maxime-rainville** 2019-08-02 05:36 UTC
