### ISSUE TITLE
File migration task for SS3 to SS4 update not working for CanViewType being null

### ISSUE THREAD

**Issue by michalkleiner** [silverstripe/silverstripe-assets#272] opened 2019-05-15 12:37 UTC
SS 4.3.3

After sspak load of SS3.7 db, some root level folders (ParentID == 0) have CanViewType column NULL, which is allowed by the db, even though the field is enum type.

The file migration task, for some reason (didn't dig deep enough) excludes these folders from migrating on the actual file system and they become inaccessible for SS4, despite the records being in db and having the correct Classname etc.

**Comment by ScopeyNZ** [comment] 2019-05-16 21:55
There's been a lot of work on file migration in 4.4 - perhaps @maxime-rainville can let you know if this is likely to have been addressed in `4.4.0-rc1`.

**Comment by maxime-rainville** [comment] 2019-05-17 03:22
We had some problems like that, which was cause by having folder with the same name but with different case. From memory, we had decided it was not worth fixing, but we might want to revisit this one.

**Comment by maxime-rainville** [comment] 2019-05-17 03:24
The original issue is here: https://github.com/silverstripe/silverstripe-assets/issues/217

@chillu Do we want to revisit this one since we found other people affected?

**Comment by michalkleiner** [comment] 2019-05-17 03:35
Just to clarify in relation to #217 - our issue is not related to the actual files or folders (or their names) at the start, but a db value of CanViewType. We only found by accident that folders with empty value (which is allowed by db constraints for the column) didn't get migrated on the file system and despite being in the database didn't show up in the assets area in the CMS. Fixing the CanViewType value after the migration didn't help as there seems to be a link between db data and physical files somehow.

**Comment by chillu** [comment] 2019-05-19 20:55
This has been fixed with https://github.com/silverstripe/silverstripe-assets/issues/249 already. Note that you'll have to use the 4.4.x-dev pre-release to get that behaviour (and run the specific migration subtask).

We can't retroactively restore values that have been unset by the radio button selection not working in secureassets from 3.x installations. It looks like any subsequent save to a folder that's been previously restricted will remove that restriction due to this bug (set `NULL` values).

> Fixing the CanViewType value after the migration didn't help as there seems to be a link between db data and physical files somehow.

I've tried this myself when filing the issue above, and setting `CanViewType` did fix the issue. If you can prove your case with a step-by-step reproduction, we can reopen this ticket.

**Closed by chillu** 2019-05-19 20:55 UTC
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/bug
