### ISSUE TITLE
File migration: Sub-folders with ten character names

### ISSUE THREAD

**Issue by flashbackzoo** [silverstripe/silverstripe-assets#329] opened 2019-09-11 00:06 UTC
## Affected Version

1.4.0 (Current CWP version)

## Description

When migrating files from 3.x to 4.4 using the `MigrateFileTask`, files located in sub-folders named with exactly ten characters fail to migrate.

`FileMigrationHelper` calls `$this->store->normalisePath($filename)` which attempts to parse the file id using each of the FileIDHelpers defined in [asset.yml](https://github.com/silverstripe/silverstripe-assets/blob/1/_config/asset.yml)

The issue is caused by a [regex in HashFileIDHelper](https://github.com/silverstripe/silverstripe-assets/blob/1/src/FilenameParsing/HashFileIDHelper.php#L82).

If the sub-folder name is exactly ten characters, the folder name is used as the hash, which gets saved to the database. The CMS is then unable to locate the file.

## Steps to Reproduce

1. Create a 3.x site
2. Load asset admin and create a folder called `example`
3. Inside the `example` folder create a new folder called `migratebad` (this can be called anything you like, but the folder name __must be exactly 10 characters long__)
4. Upload a file in `example/migratebad`
5. Create an sspak file
6. Create a 4.x site
7. Load the sspak file
8. Build the database
9. Run the `MigrateFileTask` task
10. Load asset admin and see files in `example/migratebad` have not been migrated

If you have a look at the `File` database table you'll see `migratebad` has been used as the hash.

**Comment by michalkleiner** [comment] 2019-09-11 00:23
Dupe of #269

**Comment by flashbackzoo** [comment] 2019-09-11 00:45
Ahh thanks

**Closed** 2019-09-11 00:45 UTC
