### ISSUE TITLE
Folder names hidden if browser zoom <100% (Chrome & Safari)

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-assets#437] opened 2021-03-02 11:09 UTC
When viewing the Files area in Chrome or Safari and you have the zoom level set to less than 100%, e.g. 90%, the folder names (and checkboxes) drop outside their boxes and become hidden:

![image](https://user-images.githubusercontent.com/329880/109639858-9f462180-7b47-11eb-946b-59fc09643f55.png)

_Reproduced in Silverstripe 4.7.1_

**Comment by kinglozzer** [comment] 2021-03-02 11:37
A client of ours encountered the exact same issue a few days ago!

Changing `.gallery-item--folder .gallery-item__title { width: 131px; }` to `130px` fixes it (at least as far as 50% zoom). I’ve not looked at the CSS in any detail, so I’m not sure if there’s any alternative to using fixed pixel widths

**Comment by kinglozzer** [comment] 2021-03-02 11:38
I’m going for `impact/medium` because it breaks the CMS UI, and it’s apparently quite easy to accidentally do this and not realise (our client had no idea they’d change the zoom level)

**Comment by kinglozzer** [comment] 2021-03-05 09:23
Closing as a duplicate of https://github.com/silverstripe/silverstripe-asset-admin/issues/1147

**Closed by kinglozzer** 2021-03-05 09:23 UTC
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug
