### ISSUE TITLE
MigrateFileTask corrupts files if same name but different case

### ISSUE THREAD

**Issue by altwohill** [silverstripe/silverstripe-assets#217] opened 2019-03-08 02:25 UTC
## Overview

When running the MigrateFileTask on a site I noticed that certain images were adversely affected - either completely corrupted or the wrong image would show.

On closer investigation, the CMS users have uploaded files that have the same name but different casing. 
![image](https://user-images.githubusercontent.com/629254/54003222-4d679c80-41b6-11e9-9a67-a38c3d056eed.png)

While odd, this is a valid use-case, so the migration task should support it.

## Acceptance Criteria

 * As a dev upgrading to 4.x and running the file migration task, I am informed if there are issues around file and folder case sensitivity clashes
 * The file migration task is not reliant on running on a case sensitive filesystem
 * I am informed about any renames and their consequences (direct links will break)
 * There's a special case for auto-generated `assets/Uploads` which might conflict with `assets/uploads` (merges rather than renames to `assets/uploads-2`)

## Notes

 * Case sensitive files with the same name is NOT a design goal, but rather a bug we need to avoid (through input validation and migration tasks)
 * A `file_exists()` check won't work for this, we'll need to `strtolower` in a database query

**Comment by maxime-rainville** [comment] 2019-03-08 02:48
Someone else I was helping had a similar issue with their `uploads` folder which was having casing problems with the default `Uploads` folder.

**Comment by NightJar** [comment] 2019-03-08 03:10
Relevant old issue: https://github.com/silverstripe/silverstripe-framework/issues/7416

**Comment by wilr** [comment] 2019-03-27 21:40
This is still blocking us from all deploys on CWP. In our case the existing `Uploads` folder was lowercase `assets/uploads` not `assets/Upload`. 

Paths in the database are all correct (lowercase) e.g assets/uploads/ so not sure the migration script would not pick this up correctly.

**Comment by chillu** [comment] 2019-03-31 22:23
@wilr Do you think the new ACs in the ticket description would solve your issue?

**Comment by sminnee** [comment] 2019-04-01 21:42
> This is still blocking us from all deploys on CWP. In our case the existing Uploads folder was lowercase assets/uploads not assets/Upload.

Bumping to critical @chillu

**Comment by chillu** [comment] 2019-04-01 22:46
It's literally the next thing in our backlog after doing *other* file migration things which are already in progress.

**Comment by maxime-rainville** [comment] 2019-04-02 05:19
I got a possible solution for people who are stuck and need an immediate fix. This is a bit **experimental**, so don't use on any data you don't mind loosing.

```php
<?php
use SilverStripe\Assets\File;
use SilverStripe\Dev\BuildTask;
use SilverStripe\Assets\Folder;
use SilverStripe\ORM\Queries\SQLUpdate;
use SilverStripe\Security\InheritedPermissionFlusher;

/**
 * EXPERIMENTAL - USE AT YOUR OWN RISK
 *
 * Folders imported from SS3 might end up with broken permission if there's a case conflict . This tasks reset the
 * permission of folders that have a `null` CanViewType value.
 *
 * You need to flush your cache after running this task.
 */
class MigrateFolderTask extends BuildTask
{

    private static $segment = 'MigrateFolderTask';

    protected $title = 'EXPERIMENTAL - Migrate Folders from 3.x that have a casing conflict';

    protected $description =
        'Reset the permission of folders that have a `null` CanViewType value. You\'ll need to flush your cache after' .
        'running this task.';

    public function run($request)
    {

        SQLUpdate::create(
            File::singleton()->baseTable(),
            ['CanViewType' => 'Inherit'],
            ['ISNUll(CanViewType)', 'ClassName' => Folder::class]
        )->execute();

        // This part won't work if run from the CLI, because they don't share the same cache.
        InheritedPermissionFlusher::flush();
    }
}
```

Thanks to @wilr for providing some data for me to play with.

**Comment by chillu** [comment] 2019-04-28 23:20
The issue with zero byte files when migrating with `legacy_filenames=true` has been mitigated through https://github.com/silverstripe/silverstripe-assets/pull/209/files. I don't think that explains how an asset store ended up with an `assets/uploads-2` folder though, since even before that fix it was set to `CONFLICT_OVERWRITE` and not `CONFLICT_RENAME` (which would've caused that `-2` suffix).

**Comment by chillu** [comment] 2019-04-29 00:07
3.x behaviour:
- Creating a new folder or uploading a file with the same name will rename by default (add suffix) via `File->setName()` - also used by `Folder`: https://github.com/silverstripe/silverstripe-framework/blob/3/filesystem/File.php#L658.
- On MySQL, [case sensitivity](https://dev.mysql.com/doc/refman/5.7/en/case-sensitivity.html) is determined by the collation on string comparisons. By default, that's case insensitive (`utf8_general_ci`)
- `File->updateFilesystem()` [skips renames](https://github.com/silverstripe/silverstripe-framework/blob/3/filesystem/File.php#L586) on `file_exists()`. That's dependant on the filesystem case sensitivity: https://stackoverflow.com/questions/3964793/php-case-insensitive-version-of-file-exists#3964927. So on a case sensitive filesystem, you can change `File.Filename` (not `File.Name`) to be a different casing, and it'll rename it. But you can't upload the same file with the original casing again, due to that SQL check above which is case insensitive.
- `assets/Uploads` is created through the first `UploadField` usage (not through `AssetAdmin`), based on `Upload::uploads_folder` (in this casing)
- On an ext4 case sensitive filesystem, I wasn't able to create two folders with the same name and different casing
- When you rename a folder, it'll recursively rename all the `File.Filename` entries contained in it

4.x behaviour:
- Creating a folder or filename is determined by the `AssetStore::CONFLICT_*` flags. 
- Folders are created via a [GraphQL mutation](https://github.com/silverstripe/silverstripe-asset-admin/blob/d320fa53216409ea70c0706af95a45e55ef28461/code/GraphQL/CreateFileMutationCreator.php) which just uses `File->write()`
- Files are uploaded via [AssetAdmin->apiCreateFile()](https://github.com/silverstripe/silverstripe-asset-admin/blob/6539ae414fe398c952d4c3a4e451b87badeafd1a/code/Controller/AssetAdmin.php#L278). `UploadField` is configured not to replace files by default. The `UploadReceiver` under the hood will set `AssetStore::CONFLICT_RENAME` in that case
- It gets a bit complicated from there due to the new file resolution strategies, but in general I think it's doing SQL based checks as well there.

I think we're conflating a few issues that were observed in the wild here:

1. 3.x allowed case sensitive file duplicates to be created (screenshot in initial ticket). Confirmed that's possible (on a case sensitive filesystem)
2. Migrated folders don't have a `CanViewType` (see [Maxime's fix](https://github.com/silverstripe/silverstripe-assets/issues/217#issuecomment-478848465)). @maxime-rainville Should this be a separate issue?
3. A webroot has a `assets/uploads-2` folder. Unclear how this happened, probably manual author actions?
4. Migrate with `legacy_filenames=true` causes zero bytes files. Presumably fixed through https://github.com/silverstripe/silverstripe-assets/pull/209

**Comment by chillu** [comment] 2019-04-29 00:38
I've tried to reproduce this on a case sensitive filesystem, and Maxime's current permalink pull requests:

In 3.x:
- Create `assets/Uploads`
- Upload two files with same name but different casing (not renamed)
- Rename to `assets/uploads`

In 4.x:
- `legacy_filenames=false`
- Copy files and database from 3.x, run dev/build
- Run `dev/tasks/MigrateFileTask`

Result
- `CanViewType=NULL` on folder (fixed manually to `Inherit`)
- Got two files with different casings in the folder (as expected)

Note that I have *not* created a casing conflict on folders here, but it still didn't migrate the `CanViewType` properly. I think this is

**Comment by chillu** [comment] 2019-04-29 04:51
OK, I'm closing this, and having a more focused discussions on one of the *four* things here which actually turned out to be an existing bug: https://github.com/silverstripe/silverstripe-assets/issues/249

Addressing the ACs:

> As a dev upgrading to 4.x and running the file migration task, I am informed if there are issues around file and folder case sensitivity clashes

I can't get 3.x to create case sensitivity clashes (at least through the CMS UI), so I don't think we can satisfy that AC in any way. 

> The file migration task is not reliant on running on a case sensitive filesystem

I think that's the case, but again - it doesn't matter due to the point above.

> I am informed about any renames and their consequences (direct links will break)

Can't do this, due to the above.

> There's a special case for auto-generated assets/Uploads which might conflict with assets/uploads (merges rather than renames to assets/uploads-2)

Has anyone come across `assets/uploads-2` issues? I can't reproduce this in 3.x or 4.x, even when renaming `assets/Uploads` to `assets/uploads`, and then using `UploadField` again (uses `assets/uploads`, doesn't create duplicates. There's one inconsistency in both 3.x and 4.x: On the filesystem, the folder stays in the original casing. That doesn't throw off file migration though (doesn't create duplicates).

Overall, case sensitivity has been discussed to death in https://github.com/silverstripe/silverstripe-framework/issues/7416 and https://github.com/silverstripe/silverstripe-framework/issues/7660, so not keen to repeat that. I'm purely focused on how case sensitivity might case data corruption during a 4.x upgrade - and I can't see any. So closing this ticket unless somebody has reproducible steps for the three issues above where we haven't split out another focused ticket.

**Closed by chillu** 2019-04-29 04:51 UTC
Labels: affects/v4, change/patch, impact/critical, type/bug
