### ISSUE TITLE
Image's "Title" should not go into title attribute

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-assets#129] opened 2018-04-08 14:37 UTC
When adding an Image into a HTMLEditorField, the dialog will by default put the Image's Title into the "Title text (tooltip)". It should instead go into the "Alternative text (alt)" attribute, as this is what that attribute is meant for (if the file has a descriptive name, or the user has updated the Title into something sensible). `<img>` elements are actually even illegal without an `alt` attribute, so it should at least be set as an empty string. While the `title` attribute is an optional attribute for _any_ html element, so it should not be automatically set.

I strongly suggest moving the auto-fill from `title` to `alt`, or simply not copying the Title to _any_ attribute.

(slightly edited on 12 Nov 2019 after discussion)

**Comment by maxime-rainville** [comment] 2018-04-09 04:56
Hi @JorisDebonnet 

I just had a look in SS4.1. From what I can see, if you leave the `Alternative text` field empty in the WYSIWYG, an `alt` attribute will be added to the HTML output when your WYSIWYG content is rendered in the front end. The `alt` attribute is populated with the `Title` attached to the image object.

Can you let me know if that's what you are seeing on your end?

However, it is not super clear this is happening from the CMS editor's point of view. Also, if you try to edit an image you have already inserted in the WYSIWYG, the placement information that was provided originally isn't pre-populated into the _Placement_ tab. We should take a look this.

**Comment by JorisDebonnet** [comment] 2018-04-09 07:59
You're right, the alt field is populated when the page is actually parsed. But it is indeed also a serious issue that the Image dialog does not 'remember' any properties that were filled in before - if I manually resize (drag-and-drop) an image to just the right size, but then open the dialog to change the alignment, it will reset the size (along with everything else). Perhaps an "edit image" dialog is not really implemented yet?

**Comment by dhensby** [comment] 2018-04-09 17:12
@JorisDebonnet those edit image issues sound like a bug; care to open a new issue?

**Comment by maxime-rainville** [comment] 2018-04-09 22:32
@dhensby @JorisDebonnet I've created a separate issue (#131) for loosing the placement.

**Comment by JorisDebonnet** [comment] 2018-04-10 00:13
I could give this one (`title` vs `alt`) a go, but haven't worked on any WYSIWYG integrated stuff yet. Which file would I start in? (not even sure it's in this repository o.O)

**Comment by mllngtn** [comment] 2018-09-27 03:37
Hi, I've just run into this issue today.

I think that the most standards-compliant thing to do would be to add an empty 'alt' attribute (alt="") by default, if the alt-text field is left empty.

---

This is my understanding of the guidance given here: https://html.spec.whatwg.org/dev/images.html#alt

1) The most important part is this quote: "the alt attribute's value should never contain text that could be considered the image's caption, title, or legend".  

This suggests that auto-populating the 'alt' attribute with the image's title is bad practice.

2) Although the 'alt' tag is required for all images, it should be empty (alt="") if the image is decorative.

And images are classed as 'decorative' unless the page no longer makes sense without them.

The most common examples of non-decorative images are a flow-chart, a graph, or an image with text baked into it.

A good of thumb is therefore 'if in doubt, the image is decorative', and therefore requires an empty 'alt' attribute which allows it to be skipped by assistive technologies.

3) Another advantage of adding an empty 'alt' tag by default is that SilverStripe would not be making decisions on behalf of its admin users. 

It is the responsibility of whoever is uploading images and adding them to pages to decide whether or not they are content requiring alt text.

**Comment by mr45144** [comment] 2019-09-18 07:22
Definite misunderstanding of the purpose of ALT text here and an issue that the content owner should be managing. The purpose of the alt text is to replace the information of the image in text - eg a picture titled 'Bob the Dog' may well have ALT text such as 'A black lab wearing his guidedog harness and walking to the left of his handler. His handler is blind.' The ALT should be defined by the content owner. If nothing is defined then a warning shown with a fallback of ALT="" which will then be ignored by assistive tech.

**Comment by JorisDebonnet** [comment] 2019-09-18 15:57
You're right of course, but right now a separate Alt text cannot be saved. I suppose the best solution would be to add an database field for the alt attribute (for Images), which could default to the Image's Title (which should be better than nothing in most cases), but can then be overwritten by something more descriptive.

**Comment by mr45144** [comment] 2019-09-18 22:16
All images need a place for the Alt text, I'm very surprised this has been missed. I have an open bug in with my devs to do this and in the gallery (our own imagegallery that was based on the older gallery code and uses shortcodes retains alt text but it has been dropped from the core gallery)

**Comment by mr45144** [comment] 2019-09-18 22:31
> You're right of course, but right now a separate Alt text cannot be saved. I suppose the best solution would be to add an database field for the alt attribute (for Images), which could default to the Image's Title (which should be better than nothing in most cases), but can then be overwritten by something more descriptive.

Or replaced by a Alt=""

**Comment by mllngtn** [comment] 2019-09-18 23:07
> > You're right of course, but right now a separate Alt text cannot be saved. I suppose the best solution would be to add an database field for the alt attribute (for Images), which could default to the Image's Title (which should be better than nothing in most cases), but can then be overwritten by something more descriptive.
> 
> Or replaced by a Alt=""

Yes, I agree that alt="" is the best default solution.

Rather than 'title is better than nothing', I would suggest that in the majority of cases, 'nothing is better than title', for the following reasons:

1) The image of Bob the Dog might have the title '2019-bob-final-web', or 'IMG-060919-0004', etc. These are pretty realistic examples, and would obviously make for incomprehensible alt text!

2) Even if our image does have a nice title, this doesn't mean that the title will make for nice alt text. See @mr45144's example that the same image can require very different alt text depending on context. To re-quote the relevant portion of the specs that I linked to above...  "the alt attribute's value should never contain text that could be considered the image's caption, title, or legend". 

3) The image may well be decorative, in which case alt="" is the correct solution anyway.

**Comment by brynwhyman** [comment] 2019-09-19 22:04
Hi, we're actually looking at a very similar/ duplicate issue at the moment: https://github.com/silverstripe/silverstripe-asset-admin/issues/983. 

Do you mind checking if that issue aligns with your expectations?

**Comment by mr45144** [comment] 2019-09-19 22:22
Good call @brynwhyman - have added some comments over there but suggest this thread be included in that fix.

**Comment by brynwhyman** [comment] 2019-11-12 20:12
Contrary to the title, the conversation in this issue has confirmed that the image alt text should not fall back as the image title if it is blank. https://github.com/silverstripe/silverstripe-assets/pull/338 will resolve the bug currently present.

Also check out https://github.com/silverstripe/silverstripe-asset-admin/issues/983 for other improvements made in this area.

**Comment by brynwhyman** [comment] 2019-11-12 20:12
This issue has been worked on as part of a larger initiative focused on reducing the experience debt of the SilverStripe CMS.

Thank you for taking the time to raise this issue and/ or provide feedback supporting the implementation.

This is an initiative from the teams maintaining the commercially supported module list. If you're interested to read more about this initiative and keep up with our progress have a look at our [blog post on experience debt](https://www.silverstripe.org/blog/weve-got-experience-debt-in-our-sights).

**Comment by JorisDebonnet** [comment] 2019-11-13 01:27
I have slightly edited the original post and title, because it was mainly about stopping the practice of how an Image's Title is inserted into the title attribute, while the alt attribute discussion was (originally) only secondary. I realize recent discussion has mostly been about what a default alt attribute should be (if any), but I just wanted to clarify what this issue was originally about.

**Comment by JorisDebonnet** [comment] 2019-11-13 13:59
I'm not convinced the original topic of this issue is solved, at least not by #338. The Title - as far as I can see - is still automatically inserted into the "Title text (tooltip)" in the insert-media-modal. Here's a screenshot of what I mean (guess I should have had this in the original post):

![image](https://user-images.githubusercontent.com/3286264/68770289-26574980-0626-11ea-8d35-b6aae05a0094.png)

Can this be reopened?

**Comment by dnsl48** [comment] 2019-11-13 20:11
sorry, wasn't intentional. Github closed this because the mentioned PR was talking about "resolving #129".

**Comment by brynwhyman** [comment] 2019-11-13 23:16
Hey @JorisDebonnet thank you for clarifying and updating the issue title - agree the conversation diverted a little. That makes more sense now.

**Closed** 2020-04-21 07:18 UTC
Labels: affects/v4, change/minor, impact/low, type/UX, type/enhancement
